name: Banner version migrations

on:
  pull_request:
  push:

jobs:
  mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute the BDC and AIM-AHEAD deployment migrations on MySQL
        run: >-
          tests/banner-version-migration/test.sh
          app-infrastructure/db/bdc/picsure/V10__CREATE_BANNER_VERSION.sql
          app-infrastructure/db/aim-ahead/picsure/V10__CREATE_BANNER_VERSION.sql
